### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by willthomson** [txels/ddt#21]
It would be great if you could add a license to this project. Thanks!

**Comment by lorenzph** [comment]
@gtsafas could you comment whether you agree with the proposed change? It would be great to see the licensing clearly documented within the source files and repository.

**Comment by txels** [comment]
I've made a PR with the new license https://github.com/txels/ddt/pull/24. I will merge that shortly and *maybe* take this as a chance to release as version 1.0.

**Comment by gtsafas** [comment]
@lorenzph im good with it!

**Comment by txels** [comment]
Closed by #24
