### ISSUE TITLE
Passing an iterable with test values

### ISSUE THREAD

**Issue by stefaniegoetz** [txels/ddt#27]
Exactly what I was looking for, just that I'd like to pass an interable of test values to the data decorator, like so:

```
LANGUAGES = (
    ('en', _('English')),
    ('de', _('German')),
    ('fr', _('French')),
    ('sv', _('Swedish')),
    ('tr', _('Turkish')),
)

@data(LANGUAGES)
def test_that_the_page_loads_succesfully_in_the_given_language(self, language):
    ...
```

The unpack decorator doesn't help here, as I want to run the test per language.

**Comment by stefaniegoetz** [comment]
Silly me, of course I can simply unpack the iterable before passing it:

```
@data(*LANGUAGES)
def test_that_the_page_can_be_loaded_in_the_given_language(self, language):
    ...
```

**Comment by ankostis** [comment]
You can also use #40, assuming it is merged.
