### ISSUE TITLE
Exit series of method if fail/error

### ISSUE THREAD

**Issue by CJ-Wright** [txels/ddt#31]
Would it be possible for the `@data` decorator to stop early if the test fails?  Similar to `nosetests -x` except on a method by method basis.

**Comment by txels** [comment]
DDT is not a test runner. As a class decorator, it multiplies the test cases at load time, and tries to do so in a manner that doesn't interfere with test runners. The result will be that you will have a different test case for every data value.

This makes it possible to use your test runner of choice and let it fail fast if it supports that option.

Have you tried using `nosetests -x` with `ddt`? Did you bump into any issues?

**Comment by CJ-Wright** [comment]
I did run `nosetests - x` with `ddt`, and it skipped the rest of the tests.
